metadata:
  # title: КОНФИГУРАЦИОННОЕ УПРАВЛЕНИЕ
  # subtitle: Учебное пособие
  # author: П.Н. Советов
  # date: Москва – 2021
  figureTitle: Рис.     #Заголовок для рисунков, который часто используется в LaTeX или других форматах.
  figPrefix: рис.    
  titleDelim: .
  tableTitle: Таблица   #Заголовок для таблиц, который часто используется в LaTeX или других форматах.
  tblPrefix: табл. 
  numberSections: false #Нужно ли нумеровать секции документа. На случай если разделы не пронумерованы
  sectionsDepth: 3      #Глубина нумерации разделов
  secHeaderDelim: ". "
  toc-title: Оглавление #Заголовок для оглавления
  biblatexoptions: [backend=biber, citestyle=numeric-comp] #Более мощный движок для работы с библиографией и поддержкой большего количества языков, стилей итп
  link-citations: true  #Если true, тогда ссылки на источники будут преобразованы в кликабельные ссылки в PDF и HTML выходных файлах.