metadata:
  figureTitle: Рис.     #Заголовок для рисунков, который часто используется в LaTeX или других форматах.
  figPrefix: рис.    
  titleDelim: .
  tableTitle: Таблица   #Заголовок для таблиц, который часто используется в LaTeX или других форматах.
  tblPrefix: табл. 
  numberSections: false #Нужно ли нумеровать секции документа. На случай если разделы не пронумерованы
  sectionsDepth: 3      #Глубина нумерации разделов
  secHeaderDelim: ". "
  toc-title: Оглавление #Заголовок для оглавления
  biblatexoptions: [backend=biber, citestyle=numeric-comp] #Более мощный движок для работы с библиографией и поддержкой большего количества языков, стилей итп
  bibliography: bibliography2.bib
  link-citations: true  #Если true, тогда ссылки на источники будут преобразованы в кликабельные ссылки в PDF и HTML выходных файлах.
  csl: gost-r-7-0-5-2008-numeric-iaa.csl